task: CifarFedProtopnet
synthesizer: Pattern
batch_size: 250
test_batch_size: 100
lr: 0.0001
momentum: 0.9
decay: 0
epochs: 10
scheduler_milestones:
- 30
- 50
- 100
log_interval: 100
pretrained: true
base_architecture: vgg19
img_size: 32
prototype_shape:
- 20
- 8
- 1
- 1
num_classes: 10
prototype_activation_function: log
add_on_layers_type: regular
class_specific: true
scheduler: false
poisoning_proportion: 0.5
backdoor_label: 9
loss_balance: MGDA
mgda_normalize: none
save_model: false
log: true
tb: true
report_train_loss: true
transform_train: true
fl: true
fl_no_models: 20
fl_local_epochs: 1
fl_total_participants: 20
fl_eta: 1
FGnoniid: 0
fl_sample_dirichlet: true
fl_dirichlet_alpha: 6
fl_diff_privacy: false
fl_dp_clip: null
fl_dp_noise: null
fl_number_of_adversaries: 14
fl_weight_scale: 1
eps: 0.2
aggregate: clustering
defense: true
outlier_detection: DBSCAN
distance_calculation: euclidean
block_time: 0
nogood_exit: false
poison_lr: 0.0001
baseline: false
retrain_poison: 1
poison_step_lr: false
p_attacker: 6
gb_dist: null
gb_distG: 5
gb_distB: 3
g_bStd: 1.2
gamma: 10
rearrange_client_data: true
fdr_opt: false
loss_tasks:
- protopnet
defense_warmup_rounds: 2
attack_start_round: 3
first_round_relax_defense: false
p_outlier: 5
usr_outlier2_threshold: 0.0
clustering_min_keep_ratio: 0.5
clustering_min_keep_clients: 10
min_defense_keep_rounds: 1
min_defense_keep_count: 10
data_washing_audit: true
data_washing_output_dir: /home/ismp/disk2/lo/secureML-demo/data_washing_experiment/output/cifar10_non_iid_mprobe_epoch10_audit
data_washing_batch_size: 128
